# Generated by Django 4.1.2 on 2022-10-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_is_highlighted_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Published', 'Published'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Draft', max_length=10),
        ),
    ]
